[versions]
kotlin = "2.3.0"
gradle = "8.13.2"
composeMultiplatform = "1.10.0"
material3 = "1.9.0"
dependencyVersionsPlugin = "0.53.0"
mavenPublish = "0.36.0"
dokka = "2.1.0"
androidAnnotations = "1.9.1"
coroutines = "1.10.2"
firebaseGitLiveApp = "2.4.0" # Firebase for KMP https://firebaseopensource.com/projects/gitliveapp/firebase-kotlin-sdk/
googleServicesPlugin = "4.4.4"
crashlyticsPlugin = "3.0.6"
jetbrainsLifecycle = "2.9.6"
kmpKit = "1.0.13"
supabase = "3.4.1"
ktor = "3.1.1"

# Android
androidCore = "1.17.0"
androidActivity = "1.12.2"
playServices = "21.5.0"
googleIdIdentity = "1.2.0"
androidCredentials = "1.5.0"
androidStartup = "1.2.0"

[libraries]
compose-multiplatform-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3" }
jetbrains-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "jetbrainsLifecycle" }
kmpkit = { group = "io.github.tweener", name = "kmpkit", version.ref = "kmpKit" }
firebase-auth = { group = "dev.gitlive", name = "firebase-auth", version.ref = "firebaseGitLiveApp" }

# Coroutines
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

# Android
android-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidCore" }
android-annotations = { group = "androidx.annotation", name = "annotation", version.ref = "androidAnnotations" }
android-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidActivity" }
android-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidActivity" }
android-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidStartup" }

# Google Sign In
googleSignIn-playServicesAuth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServices" }
googleSignIn-identity = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleIdIdentity" }
googleSignIn-credentials = { module = "androidx.credentials:credentials", version.ref = "androidCredentials" }
googleSignIn-credentials-playServicesAuth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidCredentials" }

# Supabase
supabase-bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "supabase" }
supabase-auth = { module = "io.github.jan-tennert.supabase:auth-kt", version.ref = "supabase" }

# Ktor
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

[bundles]
googleSignIn = ["googleSignIn-credentials", "googleSignIn-credentials-playServicesAuth", "googleSignIn-identity", "googleSignIn-playServicesAuth"]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "gradle" }
android-application = { id = "com.android.application", version.ref = "gradle" }
dependency-versions = { id = "com.github.ben-manes.versions", version.ref = "dependencyVersionsPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-nativeCocoaPods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlyticsPlugin" }
